In [12]:
import pandas as pd

In [13]:
res = pd.read_csv("result/final_predict_result.csv")

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_25676\2395393258.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  res = pd.read_csv("result/final_predict_result.csv")

In [14]:
res.sample(10)

,Unnamed: 0,GT,Predict,rating_id,user_id,movie_id,rating,timestamp,title,release_date_x,...,950,1012,997,954,1011,1016,953,1005,1018,1017
12061,12061,4.0,4.002,81936,913,168,4,1997-12-10 3:49,monty python and the holy grail,01-Jan-74,...,0,0,0,0,0,0,0,0,0,1
1320,1320,4.0,3.797,6765,144,293,4,1998-02-21 23:38,donnie brasco,28-Feb-97,...,0,0,0,0,0,0,0,0,0,1
25209,25209,5.0,4.069,43735,323,23,5,1997-11-05 14:25,taxi driver,16-Feb-96,...,0,0,0,0,0,0,0,0,0,1
17035,17035,3.0,3.714,8845,1,262,3,1997-09-24 3:23,in the company of men,01-Aug-97,...,0,0,0,0,0,0,0,0,0,1
13679,13679,4.0,4.087,85272,537,482,4,1998-01-28 23:49,some like it hot,01-Jan-59,...,0,0,0,0,0,0,0,0,0,1
15885,15885,4.0,4.174,88691,903,272,4,1998-04-13 18:53,good will hunting,01-Jan-97,...,0,0,0,0,0,0,0,0,0,1
13609,13609,3.0,3.826,66593,537,129,3,1998-01-28 23:24,bound,04-Oct-96,...,0,0,0,0,0,0,0,0,0,1
22835,22835,3.0,3.282,86372,727,544,3,1998-01-02 2:51,things to do in denver when you're dead,02-Feb-96,...,0,0,0,0,0,0,0,0,0,1
18363,18363,4.0,3.094,92477,916,583,4,1997-11-29 23:21,romeo is bleeding,01-Jan-93,...,0,0,0,0,0,0,0,0,0,1
30457,30457,3.0,3.716,38623,72,792,3,1997-11-20 14:38,bullets over broadway,01-Jan-94,...,0,0,0,0,0,0,0,0,1,0

In [15]:
len(res)

46774

In [23]:
for i in range(0, 9):
    threshold = 4.0 + i * 0.1
    result = res[(res.Predict >= threshold)]
    total = len(result)
    actual = len(result[(result.GT >= 4.0)])
    if total > 0:
        print("threshold: %.3f" % (threshold))
        print("Precision: %.3f" % (actual / total))
        print("Predicted as bigger than %d: %d" % (threshold, total))
        print("Actually bigger than %d: %d" % (threshold, actual))
        print("Total number of data: %d" % (len(res)))
        print("============================================")

threshold: 4.000
Precision: 0.808
Predicted as bigger than 4: 7994
Actually bigger than 4: 6456
Total number of data: 46774
============================================
threshold: 4.100
Precision: 0.836
Predicted as bigger than 4: 4608
Actually bigger than 4: 3850
Total number of data: 46774
============================================
threshold: 4.200
Precision: 0.854
Predicted as bigger than 4: 2375
Actually bigger than 4: 2029
Total number of data: 46774
============================================
threshold: 4.300
Precision: 0.856
Predicted as bigger than 4: 1413
Actually bigger than 4: 1209
Total number of data: 46774
============================================
threshold: 4.400
Precision: 0.892
Predicted as bigger than 4: 538
Actually bigger than 4: 480
Total number of data: 46774
============================================